<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试报告</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!--    页面样式-->
    <style type="text/css">
        /*标题样式*/
        .title {
            width: auto;
            height: 60px;
            text-align: center;
            font: bolder 38px/60px "Microsoft YaHei UI";
        }

        /*汇总信息样式*/
        .summary {
            width: 90%;
            position: absolute;
            top: 120px;
            margin-left: 5%;

        }

        .text-left {
            font: bolder 20px/30px "Microsoft YaHei UI";
        }

        .left {
            width: 50%;
            float: left;

        }

        .right {
            width: 50%;
            float: right;

        }

        .desc {
            float: left;
            width: 100%;
        }

        .list-group-item span {
            font: normal 16px/38px "Microsoft YaHei UI";
            padding: 30px;

        }

        .list-group-item {
            position: relative;
            display: block;
            padding: .4rem 1.25rem;
            background-color: #fff;
            border: 1px solid rgba(0, 0, 0, .125);
        }

        /* 执行信息样式   */
        .test_info {
            width: 90%;
            position: absolute;
            top: 900px;
            margin-left: 5%;

            color: #28a745 !important;
        }

        .table td, th {
            border: solid 2px rgba(9, 122, 51, 0.11) !important;
            padding: 0;
            line-height: 40px;
            text-align: center;

        }


        select {
            border: 0;
            padding: 0;
            margin: 0;
            height: 2em;
            width: 8em;
            margin-left: 2em;
        }

        option {
            text-align: center;
            height: 36px;
            font: none 18px/36px "Microsoft YaHei UI";
            color: #28a745 !important;
        }

        .test_log {
            background: rgba(163, 171, 189, 0.15);
            width: 100%;
            height: 50px;
            border-top: none;
            border-bottom: none;
            display: none;
            text-align: left;
        }

        .test_log td {
            text-align: left;
            height: 30px;
            margin: 0;
            padding-left: 3em;
            padding-right:3em;
            font: none 18px/24px "Microsoft YaHei UI";
            color: #9e141a;
        }

        pre {
            margin: 0;
            white-space: pre-wrap;
            white-space: -moz-pre-wrap;
            white-space: -o-pre-wrap;
            word-wrap: break-word;
        }

        /*    测试图表显示*/
        .char {
            width: 90%;
            position: absolute;
            top: 450px;
            margin-left: 5%;
            color: #28a745 !important;
        }

    </style>

</head>
<body>

<!--报告标题-->
<div class="title text-success">
    <div class="shadow-lg p-3 mb-5 bg-white rounded">35期的测试报告</div>
</div>

<!--汇总信息-->
<div class="summary">
    <p class="text-left text-success">测试结果汇总</p>
    <div class="left">
        <ul class="list-group">
            <li class="list-group-item">
                <button type="button" class="btn btn-success">测试人员</button>
                <span class="text-dark">军军</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-success">开始时间</button>
                <span class="text-dark">2021-01-07 20:47:44</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-success">执行时间</button>
                <span class="text-dark">9.93 S</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-success">用例总数</button>
                <span class="text-dark">61</span>
            </li>


        </ul>
    </div>
    <div class="right">
        <ul class="list-group">

            <li class="list-group-item">
                <button type="button" class="btn btn-success">成功用例</button>
                <span class="text-success">19</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-danger">失败用例</button>
                <span class="text-warning">35</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-warning">错误用例</button>
                <span class="text-danger">7</span>
            </li>
            <li class="list-group-item">
                <button type="button" class="btn btn-secondary">跳过用例</button>
                <span class="text-secondary">0</span>
            </li>
        </ul>
    </div>
    <div class="desc">
        <ul class="list-group">
            <li class="list-group-item">
                <button type="button" class="btn btn-success">描述信息</button>
                <span class="text-secondary">XX项目测试生成的报告</span>
            </li>
        </ul>
    </div>


</div>

<!--测试图表-->
<div class="char">
    <p class="text-left text-success">图表展示</p>
    <div id="char2" style="width: 49%;height: 400px;float: left"></div>
    <div id="char" style="width: 49%;height: 400px ;float: left"></div>
</div>

<!--详细信息-->
<div class="test_info">

    <p class="text-left text-success">详细信息</p>
    <div class="table_data">

        <table class="table">
            <thead class="bg-success text-light">
            <tr>
                <th scope="col" style="width: 5%;padding: 0">编号</th>
                <th scope="col" style="width: 20%;padding: 0">
                    <span>测试类</span>
                    <select id="testClass">
                        <option>所有</option>
                        
                            <option>TestRegister</option>
                        
                            <option>TestLogin</option>
                        
                            <option>TestRecharge</option>
                        
                            <option>TestWithdraw</option>
                        
                            <option>TestAdd</option>
                        
                            <option>TestAudit</option>
                        
                            <option>TestInvest</option>
                        
                    </select>

                </th>

                <th scope="col" style="width: 15%;padding: 0">测试方法</th>
                <th scope="col" style="width: 20%;padding: 0">用例描述</th>
                <th scope="col" style="width: 10%;padding: 0">执行时间</th>
                <th scope="col" style="width: 20%;padding: 0">

                    <span>执行结果</span>
                    <select id="testResult">
                        <option>所有</option>
                        <option class="text-success">成功</option>
                        <option class="text-danger">失败</option>
                        <option class="text-warning">错误</option>
                        <option class="text-info">跳过</option>
                    </select>

                </th>
                <th scope="col" style="width: 10%;padding: 0">详细信息</th>
            </tr>
            </thead>
            <tbody>
            
                <tr>
                    <td>1</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_01</td>
                    <td>注册成功-带注册名</td>
                    <td>0.154s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 0, 'msg': 'OK'}
实际结果： {'code': 0, 'msg': 'OK', 'data': {'id': 10048685, 'reg_name': '34254sdfs', 'mobile_phone': '13307420606'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
数据库中查询的的数量为： 1
test_register_01 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>2</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_02</td>
                    <td>成功-不带用户名</td>
                    <td>0.139s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 0, 'msg': 'OK'}
实际结果： {'code': 0, 'msg': 'OK', 'data': {'id': 10048686, 'reg_name': '小柠檬', 'mobile_phone': '13377754092'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
数据库中查询的的数量为： 1
test_register_02 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>3</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_03</td>
                    <td>不输入手机号</td>
                    <td>0.116s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 1, 'msg': '手机号为空'}
实际结果： {'code': 1, 'msg': '手机号为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_03 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>4</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_04</td>
                    <td>手机号长度10位</td>
                    <td>0.123s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 2, 'msg': '无效的手机格式'}
实际结果： {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_04 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>5</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_05</td>
                    <td>手机号长度12位</td>
                    <td>0.109s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 2, 'msg': '无效的手机格式'}
实际结果： {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_05 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>6</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_06</td>
                    <td>手机号含有非法字符</td>
                    <td>0.114s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 2, 'msg': '无效的手机格式'}
实际结果： {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_06 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>7</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_07</td>
                    <td>已注册过的手机号</td>
                    <td>0.144s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 2, 'msg': '账号已存在'}
实际结果： {'code': 2, 'msg': '账号已存在', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_07 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>8</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_08</td>
                    <td>密码7位</td>
                    <td>0.127s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 2, 'msg': '密码格式为8到16位'}
实际结果： {'code': 2, 'msg': '密码格式为8到16位', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_08 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>9</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_09</td>
                    <td>密码17位</td>
                    <td>0.129s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 2, 'msg': '密码格式为8到16位'}
实际结果： {'code': 2, 'msg': '密码格式为8到16位', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_09 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>10</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_10</td>
                    <td>不输入密码</td>
                    <td>0.114s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 1, 'msg': '密码为空'}
实际结果： {'code': 1, 'msg': '密码为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_10 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>11</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_11</td>
                    <td>注册名11位</td>
                    <td>0.136s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 2, 'msg': '用户昵称长度超过10位'}
实际结果： {'code': 2, 'msg': '用户昵称长度超过10位', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_11 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>12</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_12</td>
                    <td>类型输入非0，1内容</td>
                    <td>0.116s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 2, 'msg': '不支持的用户类型'}
实际结果： {'code': 2, 'msg': '不支持的用户类型', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_register_12 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>13</td>
                    <td class="TestRegister">TestRegister</td>
                    <td>test_register_13</td>
                    <td>不输入类型</td>
                    <td>0.142s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 0, 'msg': 'OK'}
实际结果： {'code': 0, 'msg': 'OK', 'data': {'id': 10048687, 'reg_name': '小柠檬', 'mobile_phone': '13382965034'}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
数据库中查询的的数量为： 1
test_register_13 (test_01register.TestRegister)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>14</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_01</td>
                    <td>登录成功</td>
                    <td>0.0648s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 0, 'msg': 'OK'}
实际结果： {'code': 0, 'msg': 'OK', 'data': {'id': 10005311, 'leave_amount': 4003908.64, 'mobile_phone': '13357822221', 'reg_name': '小柠檬', 'reg_time': '2020-12-31 19:36:41.0', 'type': 1, 'token_info': {'token_type': 'Bearer', 'expires_in': '2021-01-07 20:52:45', 'token': 'eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJfaWQiOjEwMDA1MzExLCJleHAiOjE2MTAwMjM5NjV9.vZUFfs3R1wm0uMtKYflczTJVsGBlk47WSiqqwdze7-aTVbGGJnjimpojHgRUpZXaWFMMjaOnbtCcRsGi8knI7Q'}}, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_login_01 (test_02login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>15</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_02</td>
                    <td>手机号为空</td>
                    <td>0.0568s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 1, 'msg': '手机号码为空'}
实际结果： {'code': 1, 'msg': '手机号码为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_login_02 (test_02login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>16</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_03</td>
                    <td>密码为空</td>
                    <td>0.0569s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 1, 'msg': '密码为空'}
实际结果： {'code': 1, 'msg': '密码为空', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_login_03 (test_02login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>17</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_04</td>
                    <td>手机号未注册</td>
                    <td>0.0678s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 1001, 'msg': '账号信息错误'}
实际结果： {'code': 1001, 'msg': '账号信息错误', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_login_04 (test_02login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>18</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_05</td>
                    <td>密码错误</td>
                    <td>0.0758s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 1001, 'msg': '账号信息错误'}
实际结果： {'code': 1001, 'msg': '账号信息错误', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_login_05 (test_02login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>19</td>
                    <td class="TestLogin">TestLogin</td>
                    <td>test_login_06</td>
                    <td>手机号格式错误</td>
                    <td>0.0559s</td>
                    
                        <td class="text-success">成功</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>预期结果: {'code': 2, 'msg': '无效的手机格式'}
实际结果： {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved'}
test_login_06 (test_02login.TestLogin)执行——>【通过】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>20</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_01</td>
                    <td>充值成功-整数</td>
                    <td>0.184s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 0, 'msg': 'OK'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_01 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 0 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>21</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_02</td>
                    <td>充值成功-1位小数</td>
                    <td>0.186s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 0, 'msg': 'OK'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_02 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 0 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>22</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_03</td>
                    <td>充值成功-2位小数</td>
                    <td>0.194s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 0, 'msg': 'OK'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_03 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 0 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>23</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_04</td>
                    <td>充值成功-50万</td>
                    <td>0.186s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 0, 'msg': 'OK'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_04 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 0 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>24</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_05</td>
                    <td>会员id为空</td>
                    <td>0.199s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 1, 'msg': '用户id为空'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_05 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>25</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_06</td>
                    <td>会员id为小数</td>
                    <td>0.19s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '数字格式化异常'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_06 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>26</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_07</td>
                    <td>充值金额为0</td>
                    <td>0.176s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_07 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>27</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_08</td>
                    <td>充值金额为负数</td>
                    <td>0.177s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_08 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>28</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_09</td>
                    <td>充值金额为空</td>
                    <td>0.174s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 1, 'msg': '金额为空'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_09 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>29</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_10</td>
                    <td>充值金额-3位小数</td>
                    <td>0.174s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '金额小数超过两位'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_10 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>30</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_11</td>
                    <td>充值金额-大于50万</td>
                    <td>0.189s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_11 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>31</td>
                    <td class="TestRecharge">TestRecharge</td>
                    <td>test_recharge_12</td>
                    <td>充值金额-非数字</td>
                    <td>0.161s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '数字格式化异常'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_recharge_12 (test_03recharge.TestRecharge)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 93, in test_recharge
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_03recharge.py", line 80, in test_recharge
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>32</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_01</td>
                    <td>提现成功-整数</td>
                    <td>0.214s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 0, 'msg': 'OK'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_01 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 0 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>33</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_02</td>
                    <td>提现成功-1位小数</td>
                    <td>0.215s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 0, 'msg': 'OK'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_02 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 0 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>34</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_03</td>
                    <td>提现成功-2位小数</td>
                    <td>0.216s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 0, 'msg': 'OK'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_03 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 0 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>35</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_04</td>
                    <td>提现成功-50万</td>
                    <td>0.214s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 0, 'msg': 'OK'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_04 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 0 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>36</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_05</td>
                    <td>会员id为空</td>
                    <td>0.194s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 1, 'msg': '会员id为空'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_05 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>37</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_06</td>
                    <td>会员id为小数</td>
                    <td>0.193s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '数值参数格式不正确'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_06 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>38</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_07</td>
                    <td>提现金额为0</td>
                    <td>0.221s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_07 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>39</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_08</td>
                    <td>提现金额为负数</td>
                    <td>0.204s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_08 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>40</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_09</td>
                    <td>提现金额为空</td>
                    <td>0.199s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 1, 'msg': '金额为空'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_09 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>41</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_10</td>
                    <td>提现金额-3位小数</td>
                    <td>0.203s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '金额小数超过两位'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_10 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>42</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_11</td>
                    <td>提现金额-大于50万</td>
                    <td>0.193s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '金额必须大于0并且小于或者等于500000'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_11 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>43</td>
                    <td class="TestWithdraw">TestWithdraw</td>
                    <td>test_withdraw_12</td>
                    <td>提现金额-非数字</td>
                    <td>0.215s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>用例执行之前，用户的余额： 4003908.64
预期结果： {'code': 2, 'msg': '数值参数格式不正确'}
实际结果： {'code': 1003, 'copyright': 'Copyright 柠檬班 © 2017-2020 湖南省零檬信息技术有限公司 All Rights Reserved', 'msg': '验签失败，缺少timestamp参数'}
用例执行之后，用户的余额： 4003908.64
test_withdraw_12 (test_04withdraw.TestWithdraw)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 87, in test_withdraw
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_04withdraw.py", line 77, in test_withdraw
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>44</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_01</td>
                    <td>加标成功</td>
                    <td>0.229s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_01 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 0 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>45</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_02</td>
                    <td>加标失败—借款人id为空</td>
                    <td>0.25s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_02 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>46</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_03</td>
                    <td>加标失败—标题为空</td>
                    <td>0.226s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_03 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>47</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_04</td>
                    <td>加标失败—借款金额为空</td>
                    <td>0.232s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_04 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>48</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_05</td>
                    <td>加标失败—年利率为空</td>
                    <td>0.238s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_05 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>49</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_06</td>
                    <td>加标失败—借款期限为空</td>
                    <td>0.193s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_06 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>50</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_07</td>
                    <td>加标失败—借款期限类型为空</td>
                    <td>0.206s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_07 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>51</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_08</td>
                    <td>加标失败—竞标天数为空</td>
                    <td>0.21s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_08 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>52</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_09</td>
                    <td>加标失败—借款人id不是当前登录用户</td>
                    <td>0.2s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_09 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 1007 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>53</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_10</td>
                    <td>加标失败—借款金额为负数</td>
                    <td>0.216s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_10 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>54</td>
                    <td class="TestAdd">TestAdd</td>
                    <td>test_add_11</td>
                    <td>加标失败—借款金额为小数</td>
                    <td>0.22s</td>
                    
                        <td class="text-danger">失败</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>调用接口之前的项目个数： 185
调用接口之后的项目个数： 185
test_add_11 (test_05add.TestAdd)执行——>【失败】
</pre>
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 615, in run
    testMethod()
</pre>
                        

                            <pre>  File "C:\python37\lib\site-packages\unittestreport\core\dataDriver.py", line 17, in wrapper
    return func(self, params, *args, **kwargs)
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 63, in test_add
    raise e
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_05add.py", line 53, in test_add
    self.assertEqual(expected['code'], res['code'])
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
</pre>
                        

                            <pre>AssertionError: 2 != 1003
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>55</td>
                    <td class="TestAudit">TestAudit</td>
                    <td>test_audit_01</td>
                    <td>审核通过</td>
                    <td>0.0484s</td>
                    
                        <td class="text-warning">错误</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 611, in run
    self.setUp()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_06audit.py", line 42, in setUp
    self.add_project()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\fixture.py", line 65, in add_project
    cls.loan_id = jsonpath(res, '$..id')[0]
</pre>
                        

                            <pre>TypeError: 'bool' object is not subscriptable
</pre>
                        

                            <pre>test_audit_01 (test_06audit.TestAudit)执行——>【错误Error】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>56</td>
                    <td class="TestAudit">TestAudit</td>
                    <td>test_audit_02</td>
                    <td>审核不通过</td>
                    <td>0.0488s</td>
                    
                        <td class="text-warning">错误</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 611, in run
    self.setUp()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_06audit.py", line 42, in setUp
    self.add_project()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\fixture.py", line 65, in add_project
    cls.loan_id = jsonpath(res, '$..id')[0]
</pre>
                        

                            <pre>TypeError: 'bool' object is not subscriptable
</pre>
                        

                            <pre>test_audit_02 (test_06audit.TestAudit)执行——>【错误Error】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>57</td>
                    <td class="TestAudit">TestAudit</td>
                    <td>test_audit_03</td>
                    <td>项目不待审核状态</td>
                    <td>0.0635s</td>
                    
                        <td class="text-warning">错误</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 611, in run
    self.setUp()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_06audit.py", line 42, in setUp
    self.add_project()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\fixture.py", line 65, in add_project
    cls.loan_id = jsonpath(res, '$..id')[0]
</pre>
                        

                            <pre>TypeError: 'bool' object is not subscriptable
</pre>
                        

                            <pre>test_audit_03 (test_06audit.TestAudit)执行——>【错误Error】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>58</td>
                    <td class="TestAudit">TestAudit</td>
                    <td>test_audit_04</td>
                    <td>参数approved_or_not为空</td>
                    <td>0.0498s</td>
                    
                        <td class="text-warning">错误</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 611, in run
    self.setUp()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_06audit.py", line 42, in setUp
    self.add_project()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\fixture.py", line 65, in add_project
    cls.loan_id = jsonpath(res, '$..id')[0]
</pre>
                        

                            <pre>TypeError: 'bool' object is not subscriptable
</pre>
                        

                            <pre>test_audit_04 (test_06audit.TestAudit)执行——>【错误Error】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>59</td>
                    <td class="TestAudit">TestAudit</td>
                    <td>test_audit_05</td>
                    <td>项目id为空</td>
                    <td>0.0569s</td>
                    
                        <td class="text-warning">错误</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 611, in run
    self.setUp()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_06audit.py", line 42, in setUp
    self.add_project()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\fixture.py", line 65, in add_project
    cls.loan_id = jsonpath(res, '$..id')[0]
</pre>
                        

                            <pre>TypeError: 'bool' object is not subscriptable
</pre>
                        

                            <pre>test_audit_05 (test_06audit.TestAudit)执行——>【错误Error】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>60</td>
                    <td class="TestAudit">TestAudit</td>
                    <td>test_audit_06</td>
                    <td>项目id不存在</td>
                    <td>0.0588s</td>
                    
                        <td class="text-warning">错误</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\case.py", line 611, in run
    self.setUp()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_06audit.py", line 42, in setUp
    self.add_project()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\fixture.py", line 65, in add_project
    cls.loan_id = jsonpath(res, '$..id')[0]
</pre>
                        

                            <pre>TypeError: 'bool' object is not subscriptable
</pre>
                        

                            <pre>test_audit_06 (test_06audit.TestAudit)执行——>【错误Error】
</pre>
                        
                        
                    </td>
                </tr>
            
                <tr>
                    <td>61</td>
                    <td class="TestInvest">TestInvest</td>
                    <td>setUpClass </td>
                    <td>None</td>
                    <td>0</td>
                    
                        <td class="text-warning">错误</td>
                    
                    <td>
                        <button type="button" class="btn btn-success btn_info">查看详情</button>
                    </td>
                </tr>

                <tr class="test_log">

                    <td colspan="7" class="small text-muted" style=" word-wrap:break-word; word-break:break-all">
                        

                            <pre>Traceback (most recent call last):
</pre>
                        

                            <pre>  File "C:\python37\lib\unittest\suite.py", line 163, in _handleClassSetUp
    setUpClass()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\test_07invest.py", line 68, in setUpClass
    cls.add_project()
</pre>
                        

                            <pre>  File "C:\project\python_35\py35_28day_apiV3\testcases\fixture.py", line 65, in add_project
    cls.loan_id = jsonpath(res, '$..id')[0]
</pre>
                        

                            <pre>TypeError: 'bool' object is not subscriptable
</pre>
                        
                        
                    </td>
                </tr>
            

            </tbody>
        </table>
    </div>

    <div style="height: 200px"></div>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>

<script>
    var tbodyTr = $('tbody tr');
    var testResult = $("#testResult");
    var testClass = $("#testClass");
    <!--    用例执行详细信息显示切换-->
    $(".btn_info").click(function () {
        $(this).parent().parent().next().toggle();

    });
    // 当选择用例类之后触发
    testClass.change(function () {
        var cls = $(this).val();
        var res = testResult.val();
        elementDisplay(cls, res);
        sort()
    });
    testResult.change(function () {
        var res = $(this).val();
        var cls = testClass.val();
        elementDisplay(cls, res);
        sort()
    });

    function elementDisplay(cls, res) {
        // 用例数据的显示
        if (cls === "所有") {
            if (res === "所有") {
                tbodyTr.has('button').show();
            } else if (res === '成功') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-success').show()

            } else if (res === '失败') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-danger').show()

            } else if (res === '错误') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-warning').show()

            } else if (res === '跳过') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.text-info').show()
            }
        } else {
            if (res === "所有") {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').show()
            } else if (res === '成功') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-success').show()
            } else if (res === '失败') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-danger').show()
            } else if (res === '错误') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-warning').show()
            } else if (res === '跳过') {
                tbodyTr.hide();
                tbodyTr.has('button').has('.' + cls + '').has('.text-info').show()
            }
        }
    }

    function sort() {
        //重新排列显示序号
        // 选择所有可以见的tr
        var visibleTr = tbodyTr.filter(":visible");

        visibleTr.each(function (index, element) {
            element.firstElementChild.innerHTML = index + 1;

        })

    }


</script>

<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('char'));
    var myChart2 = echarts.init(document.getElementById('char2'));
    // 指定图表的配置项和数据
    option = {
        color: ['#00a10a', '#ddb518', 'rgba(204,46,41,0.73)', '#85898c'],
        tooltip: {
            trigger: 'item',
            formatter: '{a} <br/>{b}: {c} ({d}%)'
        },
        legend: {
            orient: 'vertical',
            left: 10,
            data: ['通过', '失败', '错误', '跳过']
        },
        series: [
            {
                name: '测试结果',
                type: 'pie',
                radius: ['50%', '70%'],
                avoidLabelOverlap: false,
                label: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    label: {
                        show: true,
                        fontSize: '30',
                        fontWeight: 'bold'
                    }
                },
                labelLine: {
                    show: false
                },
                data: [
                    {value: 19, name: '通过'},
                    {value: 35, name: '失败'},
                    {value: 7, name: '错误'},
                    {value: 0, name: '跳过'}
                ]
            }
        ]
    };
    option2 = {
        tooltip: {
            formatter: '{a} <br/>{b} : {c}%'
        },
        toolbox: {
            feature: {
                restore: {},
                saveAsImage: {}
            }
        },
        series: [
            {
                name: '测试结果',
                type: 'gauge',
                detail: {formatter: '31.15%'},
                data: [{value: '31.15', name: '用例通过率'}],
                axisLine: {
                    lineStyle: {
                        color: [
                            [0.2, '#c20000'],
                            [0.8, '#ddb518'],
                            [1, '#00a10a']]
                    }
                }
            }
        ]
    };


    myChart2.setOption(option2);
    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>


</body>
</html>