{"name": "test_demo888[11]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 11 > 20", "trace": "self = <test_demo3.TestDome999 object at 0x0E93EFB0>, item = 11\n\n    @pytest.mark.parametrize('item', cases)\n    def test_demo888(self, item):\n>       assert item > 20\nE       assert 11 > 20\n\ntestcase\\test_demo3.py:27: AssertionError"}, "parameters": [{"name": "item", "value": "11"}], "start": 1610767548622, "stop": 1610767548623, "uuid": "30062c90-b3a5-446f-b2df-2f43f353610b", "historyId": "82d439fd12a6f1f30f17918caa93137e", "testCaseId": "1650fc4990c3977bfa462cebf092ff59", "fullName": "testcase.test_demo3.TestDome999#test_demo888", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_demo3"}, {"name": "subSuite", "value": "TestDome999"}, {"name": "host", "value": "MuSen"}, {"name": "thread", "value": "6004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_demo3"}]}